import { Project, EducationMilestone, SkillCategory, StatItem } from './types';

export const PERSONAL_INFO = {
  name: 'Niket Raj',
  title: 'Full-Stack Developer & DevOps Enthusiast',
  tagline: 'Building production-grade cloud architectures & visually stunning user experiences.',
  email: 'niketrajkvs@gmail.com',
  github: 'https://github.com/Niketraj08',
  linkedin: 'https://www.linkedin.com/in/niket-raj-aab9a5265/',
  college: 'Gandhi Engineering College',
  branch: 'Computer Science and Engineering (CSE)',
  batch: '2022 – 2026',
  bio: 'Final-year Computer Science student passionate about system design, web technology, and developer tooling. Experienced in building full-stack applications with high-fidelity frontend layouts and cloud-native integrations. Always optimizing for sub-second load times and intuitive user paths.',
  location: 'Bhubaneswar, India',
};

export const STATS: StatItem[] = [
  {
    id: 'projects',
    label: 'Projects Completed',
    value: 16,
    suffix: '+',
    description: 'Full-stack applications, CLI utilities, & APIs built.',
  },
  {
    id: 'technologies',
    label: 'Technologies Mastered',
    value: 24,
    description: 'Languages, frameworks, libraries, & DevOps tools.',
  },
  {
    id: 'certifications',
    label: 'Certifications',
    value: 8,
    suffix: '',
    description: 'Cloud, DSA, and full-stack development achievements.',
  },
  {
    id: 'years_learning',
    label: 'Years of Dev Experience',
    value: 4,
    suffix: '',
    description: 'Active software engineering, testing, & architecture exploration.',
  },
];

export const TECH_STACK = [
  'React', 'TypeScript', 'Node.js', 'Express', 'Tailwind CSS', 'Next.js', 
  'Framer Motion', 'Git', 'GitHub', 'Python', 'Java', 'C++', 'SQL'
];

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'languages',
    title: 'Core Languages',
    description: 'Syntaxes and environments utilized for systems and services.',
    skills: [
      { name: 'C++', level: 70, iconName: 'Code' },
      { name: 'JavaScript', level: 70, iconName: 'Cpu' },
      { name: 'TypeScript', level: 65, iconName: 'Code' },
      { name: 'Java', level: 60, iconName: 'Hash' },
      { name: 'SQL', level: 60, iconName: 'Database' },
      { name: 'Python', level: 50, iconName: 'Terminal' },
    ],
  },
  {
    id: 'frameworks',
    title: 'Frameworks & Libraries',
    description: 'Tools used to structure client layers and backend APIs.',
    skills: [
      { name: 'React', level: 85, iconName: 'Layers' },
      { name: 'Framer Motion', level: 80, iconName: 'Wind' },
      { name: 'Tailwind CSS', level: 90, iconName: 'Palette' },
      { name: 'Node.js / Express', level: 75, iconName: 'Server' },
      { name: 'Next.js', level: 60, iconName: 'Wind' },
    ],
  },
  {
    id: 'devops',
    title: 'Cloud & Infrastructure',
    description: 'Deployment, orchestration, and continuous development tooling.',
    skills: [
      { name: 'Git', level: 90, iconName: 'GitBranch' },
      { name: 'GitHub', level: 88, iconName: 'Github' },
    ],
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'saas-dashboard',
    title: 'SaaS Telemetry Admin',
    description: 'A multi-tenant system telemetry and visitor analytics dashboard. Processes custom web-beacon payloads in real time with beautiful visual stream insights and threshold alerts.',
    category: 'Full-Stack / DevOps',
    tech: ['React', 'TypeScript', 'Node.js', 'Express', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Niketraj08/saas-dashboard',
    liveUrl: 'https://github.com/Niketraj08/saas-dashboard',
    metric: '99.9% uptime tracking',
  },
  {
    id: 'mern-chat-app',
    title: 'MERN Real-Time Workspace',
    description: 'A high-speed real-time collaborative workspace with custom live room triggers, multi-party typing notifications, and AES-256 end-to-end encrypted message pipelines.',
    category: 'Full-Stack / Systems',
    tech: ['React', 'Node.js', 'Express', 'MongoDB', 'Socket.io', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Niketraj08/mern-chat-app',
    liveUrl: 'https://github.com/Niketraj08/mern-chat-app',
    metric: 'Sub-30ms socket latency',
  },
  {
    id: 'nextjs-ecommerce',
    title: 'Fullstack NextJS Commerce Portal',
    description: 'A modern lightweight headless e-commerce experience integrating Stripe payment intents, sub-second ISR cache invalidation hooks, and custom admin stock analytics logs.',
    category: 'Full-Stack / Systems',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Stripe API', 'Prisma', 'PostgreSQL'],
    githubUrl: 'https://github.com/Niketraj08/nextjs-ecommerce',
    liveUrl: 'https://github.com/Niketraj08/nextjs-ecommerce',
    metric: '98 PageSpeed rating',
  },
  {
    id: 'secure-auth-api',
    title: 'Secured Token Auth Middleware',
    description: 'A highly optimized token rotation authentication module supporting secure cookie propagation, CSRF handshake guards, and multi-tenant rate limiting endpoints.',
    category: 'Cloud Native / Systems',
    tech: ['Node.js', 'Express', 'JWT', 'Redis', 'TypeScript'],
    githubUrl: 'https://github.com/Niketraj08/secure-auth-api',
    liveUrl: 'https://github.com/Niketraj08/secure-auth-api',
    metric: 'Sub-15ms handshake logs',
  },
  {
    id: 'gandhi-college-portal',
    title: 'Gandhi College Campus Portal',
    description: 'A comprehensive campus community and administration web portal, supporting real-time notices, assignment uploads, and grading rosters for Gandhi Engineering College.',
    category: 'Full-Stack / Systems',
    tech: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Niketraj08/gandhi-college-portal',
    liveUrl: 'https://github.com/Niketraj08/gandhi-college-portal',
    metric: '1,200+ Active Students',
  },
  {
    id: 'algorithm-visualizer-cpp',
    title: 'Algorithms Visualizer Core',
    description: 'Interactive sorting and pathfinding visualizer with customized console renders and execution timers built in modern object-oriented design.',
    category: 'Cloud Native / Systems',
    tech: ['C++', 'CLI Graphics', 'STL', 'OOP', 'GDB'],
    githubUrl: 'https://github.com/Niketraj08/algorithm-visualizer-cpp',
    liveUrl: 'https://github.com/Niketraj08/algorithm-visualizer-cpp',
    metric: '50+ DSA Solutions',
  },
  {
    id: 'aws-devops-pipeline',
    title: 'Automated CI/CD AWS Pipeline',
    description: 'Production-ready continuous integration and automated deployment orchestrations. Configures Docker image layering, remote health tests, and target instance restarts.',
    category: 'Full-Stack / DevOps',
    tech: ['GitHub Actions', 'Docker', 'AWS S3', 'Bash', 'YAML'],
    githubUrl: 'https://github.com/Niketraj08/aws-devops-pipeline',
    liveUrl: 'https://github.com/Niketraj08/aws-devops-pipeline',
    metric: '100% automated CI/CD',
  },
  {
    id: 'hotel-booking-mern',
    title: 'Serene Suite Hotel Portal',
    description: 'Complete hotel booking engine with robust search filters, checkout carts, custom database aggregates, and stripe payment gates.',
    category: 'Full-Stack / Systems',
    tech: ['MongoDB', 'Express', 'React', 'Node.js', 'Redux', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Niketraj08/hotel-booking-mern',
    liveUrl: 'https://github.com/Niketraj08/hotel-booking-mern',
    metric: 'Sub-50ms queries',
  },
  {
    id: 'devops-monitoring-agent',
    title: 'Microservice Telemetry Agent',
    description: 'A lightweight Node.js telemetry listener that scrapes system loads and streams performance stats to a central live dashboard using WebSockets.',
    category: 'Full-Stack / DevOps',
    tech: ['Node.js', 'Bash', 'Redis', 'Socket.io', 'React'],
    githubUrl: 'https://github.com/Niketraj08/devops-monitoring-agent',
    liveUrl: 'https://github.com/Niketraj08/devops-monitoring-agent',
    metric: 'Under 1% CPU overhead',
  },
  {
    id: 'nextjs-portfolio',
    title: 'Creative Terminal Portfolio',
    description: 'A terminal-themed next generation portfolio featuring dynamic theme styles, framer motion interactive boards, and structured layouts.',
    category: 'Full-Stack / Systems',
    tech: ['Next.js', 'TypeScript', 'Framer Motion', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Niketraj08/nextjs-portfolio',
    liveUrl: 'https://github.com/Niketraj08/nextjs-portfolio',
    metric: '100% PageSpeed Core',
  },
  {
    id: 'cpp-keyvalue-store',
    title: 'Concurrent Key-Value Engine',
    description: 'High performance key-value store built from scratch in C++. Supports transactional thread-safe updates, persistent text logs, and custom lock mechanisms.',
    category: 'Cloud Native / Systems',
    tech: ['C++', 'File I/O', 'Concurrency', 'Hash Map'],
    githubUrl: 'https://github.com/Niketraj08/cpp-keyvalue-store',
    liveUrl: 'https://github.com/Niketraj08/cpp-keyvalue-store',
    metric: '20,000 writes/sec',
  },
  {
    id: 'realtime-collaborative-board',
    title: 'Interactive Pixel Whiteboard',
    description: 'An interactive canvas that broadcasts real-time drawing operations across concurrent sessions using socket pipelines and custom room routing.',
    category: 'Full-Stack / Systems',
    tech: ['React', 'WebSockets', 'Node.js', 'Canvas API', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Niketraj08/realtime-collaborative-board',
    liveUrl: 'https://github.com/Niketraj08/realtime-collaborative-board',
    metric: 'Sub-10ms broadcast sync',
  },
];

export const EDUCATION: EducationMilestone[] = [
  {
    id: 'year1',
    period: '2022 – 2023',
    title: 'Foundation & Algorithms',
    institution: 'Gandhi Engineering College (GEC)',
    description: 'Began Bachelor of Technology in Computer Science and Engineering. Mastered Object-Oriented Programming, Data Structures, and relational databases. Achieved top ranks in regional competitive programming.',
    badge: 'GPA: 8.9',
    achievements: [
      'Mastered core Java and Python algorithms',
      'Secured 1st Prize in GEC Code-Sprint hackathon',
      'Elected CSE branch representative',
    ],
  },
  {
    id: 'year2',
    period: '2023 – 2024',
    title: 'Full-Stack Core & Databases',
    institution: 'Gandhi Engineering College (GEC)',
    description: 'Ventured deeply into web architectures. Explored Express, Node, RESTful design principles, and client state orchestration. Designed multiple databases in PostgreSQL and MongoDB for class projects.',
    badge: 'Full-Stack Specialization',
    achievements: [
      'Built a custom campus newsletter app with 500+ users',
      'Completed database design & relational integrity blueprints',
      'Earned professional developer certifications in React',
    ],
  },
  {
    id: 'year3',
    period: '2024 – 2025',
    title: 'Cloud Architectures & DevOps',
    institution: 'Gandhi Engineering College (GEC)',
    description: 'Studied Advanced System Design and DevOps workflows. Implemented Docker containerization, Kubernetes local cluster scheduling, and continuous deployment pipelines.',
    badge: 'AWS Certified',
    achievements: [
      'Developed and deployed scalable API routing services',
      'Designed self-healing workflows using container hooks',
      'Led an engineering project team of 4 peers for final year outline',
    ],
  },
  {
    id: 'year4',
    period: '2025 – 2026',
    title: 'Final Year & Graduation',
    institution: 'Gandhi Engineering College (GEC)',
    description: 'Completing the engineering curriculum. Focusing on enterprise SaaS development, telemetry, artificial intelligence API orchestration, and real-time dashboard analytics. Seeking high-impact internship opportunities.',
    badge: 'Final-Year Capstone',
    achievements: [
      'Currently developing SaaS Pulse and GenAI Architect as major project',
      'Actively tutoring 50+ junior students in modern React and TypeScript',
      'On track to graduate with excellent cumulative academic honors',
    ],
  },
];
